baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"


ignorefiles = [ "dedicated/.*" ]
[params]
  company = "OVH"
  # hideDedicated = true


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "borland"
    tabWidth = 4

unsafeHTML = true
