baseURL: /
languageCode: en-us
title: avocadocs documentation theme

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: borland
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true

enableEmoji: true

params:
    # favicon: "img/Platformsh_icon_black.svg"
    favicon: "img/favicon.ico"
    # favicon: "img/avocado-icon-dark.svg"
    # logo: "img/avocadocs-light.svg"
    logo: "img/Platformsh_logo_white.svg"
