# General
baseURL = "/"
title = "docshugokit"
theme = "hugo-docsuikit"
themesdir = "../.."

[params]
  author = "Chad Carlson"
  version = "v1.0.0"
  description = "Hugo documentation theme using Docs UI Kit Bootstrap templates"
  docstyle = "docs2"
  title = "Docs"

  [params.home]
    section = "introduction"
    title = "Introduction"
    
  [params.books]
    [params.books.help]
      title = "Help"
      section = "help"
      docstyle = "docs3"
      weight = -110
    [params.books.basic]
      title = "Hugo"
      section = "basic"
      docstyle = "docs1"
      weight = -100
    [params.books.personalize]
      title = "Personalize"
      section = "personalize"
      docstyle = "platformsh"
      weight = -90
    [params.books.articles]
      title = "Articles"
      section = "articles"
      docstyle = "article"
      weight = -80
    [params.books.faq]
      title = "FAQ"
      section = "faq"
      docstyle = "faq"
      weight = -70
    [params.books.platformsh]
      title = "Deploy"
      section = "platformsh"
      docstyle = "platformsh"
      weight = -60

# Language Configuration
[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 10
  [languages.li]
    contentDir = "content/lorem"
    languageName = "Lorem Ipsum"
    weight = 20

# Syntax highlighting
[markup]
  [markup.highlight]
    style = "friendly"










# [permalinks]
  # docs = "/:title"
  # "" = "/docs"


  # (Optional, default 6) Set how many table of contents levels to be showed on page.
  # Use false to hide ToC, note that 0 will default to 6 (https://gohugo.io/functions/default/)
  # You can also specify this parameter per page in front matter
  # BookToC = 3

  # (Optional, default none) Set the path to a logo for the book. If the logo is
  # /static/logo.png then the path would be logo.png
  # BookLogo = 'logo.png'

  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  # BookMenuBundle = '/menu'

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to '*' to render all sections to menu
  # BookSection = 'docs'

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  # BookRepo = 'https://github.com/alex-shpak/hugo-book'

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Path must point to 'content' directory of repo.
  # BookEditPath = 'edit/master/exampleSite/content'

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  # BookDateFormat = 'Jan 2, 2006'

  # (Optional, default true) Enables search function with flexsearch,
  # Index is built on fly, therefore it might slowdown your website.
  # BookSearch = true
